import os, mysql.connector
from pick import pick
import random

def cls():
    os.system("cls")

try:
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        password="abhinav07"
    )
    mycursor = mydb.cursor()
    mycursor.execute("CREATE DATABASE IF NOT EXISTS finex")
    mycursor.execute("USE finex")
    mycursor.execute("CREATE TABLE IF NOT EXISTS orgs (orgID int primary key, orgName varchar(30), orgAddress varchar(500), orgEmail varchar(100), orgPassword varchar(500))")
except:
    print("There was a problem with the MySQL server")
    exit()

print("Welcome to Finex - Accounting Software")
print("Developed by ASA Finserve")
option, index = pick(["Login", "Signup", "About", "Exit"], "Main Menu")
if option=="Signup":
    cls()
    orgID = random.randint(10000,99999)
    mycursor.execute(f"SELECT orgID from orgs where orgID={orgID}")
    myresult = mycursor.fetchall()
    if myresult!=[]:
        orgID = random.randint(10000,99999)
    orgName = input("Enter your organisation's name")
    orgAddress = input("Enter your organisation's registered address \n(This will be used in the header of various reports generated by Finex)\n")
    orgEmail = input("Enter your organisation's email ID (This is used for auto sending of reports)")
    orgPassword = input("Enter a secure password for this organisation")
    length = len(orgPassword)
    mycursor.execute(f"SELECT md5('{orgPassword}')")
    myresult = (mycursor.fetchall()[0])
    for password in myresult:
        orgPassword=password
    mycursor.execute(f"INSERT INTO orgs VALUES({orgID}, '{orgName}', '{orgAddress}', '{orgEmail}', '{orgPassword}')")
    mydb.commit()
    print(f"Success! Your organisation {orgName} has been added successfully. Please remember your Organisation ID and Password carefully\nOrganisation ID : {orgID}\nPassword : ", end="")
    print("*"*length)